application:
  # dev开发环境 test测试环境 prod线上环境
  mode: dev
  # 服务器ip，默认使用 0.0.0.0
  host: 0.0.0.0
  # 服务名称
  name: go-code
  # 端口号
  port: 8000 # 服务端口号
  readtimeout: 1
  writertimeout: 2
  # 数据权限功能开关
  enabledp: false
database:
  # 数据库类型 mysql，sqlite3， postgres
  driver: mysql
  host: 127.0.0.1
  port: 3306
  password: 123456
  dbname: go-practice